
TRANS = {
    'en': {
        'welcome': "Welcome to ET Honey Trading! Please choose an option:",
        'register': "🧍 Register",
        'profile': "👤 Profile",
        'order': "🛒 Make Order",
        'feedback': "✍️ Feedback",
        'contact_support': "📞 Contact Support",
        'about': "ℹ️ About",
        'blog': "📰 GPBlog",
        'select_language': "Please select your language / ቋንቋ ይምረጡ:",
        'language_set': "Language set to English.",
        'register_intro': "Let's get you registered! First, please enter your *Full Name*:",
        'name_too_short': "Name is too short. Please enter your full name:",
        'enter_phone': "Great! Now, please enter your *Phone Number*:",
        'invalid_phone': "Please enter a valid phone number (digits only):",
        'enter_email': "Thanks! Please enter your *Email Address* (or type 'skip' to skip):",
        'invalid_email': "Please enter a valid email address or type 'skip':",
        'enter_region': "Please enter your *Region/City*:",
        'customer_type_prompt': "Are you a *New* or *Returning* customer?",
        'new_customer': "New Customer",
        'returning_customer': "Returning Customer",
        'confirm_reg_title': "*Confirm Registration Details:*",
        'confirm': "✅ Confirm",
        'cancel': "❌ Cancel",
        'reg_cancelled': "Registration cancelled.",
        'reg_success': "✅ Registration successful! You can now order products.",
        'order_now_prompt': "Would you like to order now?",
        'order_now': "Order Now",
        'order_later': "Later",
        'order_later_msg': "Okay! You can order anytime from the main menu.",
        'choose_product': "Please choose a product:",
        'choose_quantity': "Please choose a quantity:",
        'enter_address': "Please enter your delivery address:",
        'choose_payment': "Please choose a payment method:",
        'order_confirm_title': "*Confirm Order Details:*",
        'submit_order': "✅ Submit Order",
        'order_cancelled': "Order cancelled.",
        'order_success': "✅ Order submitted successfully! Pending admin approval.",
        'order_rejected': "❌ Your Order #{id} could not be processed. Please contact support.",
        'order_approved': "🎉 Your Order #{id} has been confirmed! We are processing it.",
        'not_registered': "You need to register first to use this feature. Please use the /register command.",
        'pending_approval': "Your registration is pending admin approval.",
        'account_deleted': "Your account is deleted.",
        'admin_dashboard': "Admin Dashboard",
        'about_text': "*About ET Honey Trading*\n\nWe provide high quality honey products from Ethiopia.",
        'skip': "Skip"
    },
    'am': {
        'welcome': "እንኳን ወደ ኢትዮ ማር ንግድ በደህና መጡ! እባክዎ አማራጭ ይምረጡ:",
        'register': "🧍 ይመዝገቡ",
        'profile': "👤 መገለጫ",
        'order': "🛒 ይዘዙ",
        'feedback': "✍️ አስተያየት",
        'contact_support': "📞 ድጋፍ ያግኙ",
        'about': "ℹ️ ስለ እኛ",
        'blog': "📰 GPBlog",
        'select_language': "ቋንቋ ይምረጡ / Please select your language:",
        'language_set': "ቋንቋው ወደ አማርኛ ተቀይሯል።",
        'register_intro': "ምዝገባ እንጀምር! መጀመሪያ፣ እባክዎ *ሙሉ ስምዎን* ያስገቡ:",
        'name_too_short': "ስሙ በጣም አጭር ነው። እባክዎ ሙሉ ስምዎን ያስገቡ:",
        'enter_phone': "ጥሩ! አሁን፣ እባክዎ *ስልክ ቁጥርዎን* ያስገቡ:",
        'invalid_phone': "እባክዎ ትክክለኛ ስልክ ቁጥር ያስገቡ (ቁጥሮችን ብቻ):",
        'enter_email': "አመሰግናለሁ! እባክዎ *ኢሜይል አድራሻዎን* ያስገቡ (ወይም ለመዝለል 'skip' ብለው ይጻፉ):",
        'invalid_email': "እባክዎ ትክክለኛ ኢሜይል ያስገቡ ወይም 'skip' ብለው ይጻፉ:",
        'enter_region': "እባክዎ *ክልል/ከተማ* ያስገቡ:",
        'customer_type_prompt': "እርስዎ *አዲስ* ወይስ *ነባር* ደንበኛ ነዎት?",
        'new_customer': "አዲስ ደንበኛ",
        'returning_customer': "ነባር ደንበኛ",
        'confirm_reg_title': "*የምዝገባ ዝርዝሮችን ያረጋግጡ:*",
        'confirm': "✅ አረጋግጥ",
        'cancel': "❌ ሰርዝ",
        'reg_cancelled': "ምዝገባ ተሰርዟል።",
        'reg_success': "✅ ምዝገባ ተሳክቷል! አሁን ማዘዝ ይችላሉ።",
        'order_now_prompt': "አሁን ማዘዝ ይፈልጋሉ?",
        'order_now': "አሁን ይዘዙ",
        'order_later': "በኋላ",
        'order_later_msg': "እሺ! ከዋናው ሜኑ በማንኛውም ጊዜ ማዘዝ ይችላሉ።",
        'choose_product': "እባክዎ ምርት ይምረጡ:",
        'choose_quantity': "እባክዎ መጠን ይምረጡ:",
        'enter_address': "እባክዎ የመላኪያ አድራሻዎን ያስገቡ:",
        'choose_payment': "እባክዎ የመክፈያ ዘዴ ይምረጡ:",
        'order_confirm_title': "*የትዕዛዝ ዝርዝሮችን ያረጋግጡ:*",
        'submit_order': "✅ ትዕዛዝ አስገባ",
        'order_cancelled': "ትዕዛዝ ተሰርዟል።",
        'order_success': "✅ ትዕዛዝ በተሳካ ሁኔታ ገብቷል! የአስተዳዳሪ ማረጋገጫ በመጠባበቅ ላይ።",
        'order_rejected': "❌ ትዕዛዝ #{id} ሊስተናገድ አልቻለም። እባክዎ ድጋፍን ያግኙ።",
        'order_approved': "🎉 ትዕዛዝ #{id} ተረጋግጧል! እያዘጋጀነው ነው።",
        'not_registered': "ይህንን ባህሪ ለመጠቀም መጀመሪያ መመዝገብ አለብዎት። እባክዎ /register የሚለውን ትዕዛዝ ይጠቀሙ።",
        'pending_approval': "ምዝገባዎ የአስተዳዳሪ ማረጋገጫ በመጠባበቅ ላይ ነው።",
        'account_deleted': "መለያዎ ተሰርዟል።",
        'admin_dashboard': "የአስተዳዳሪ ዳሽቦርድ",
        'about_text': "*ስለ ኢትዮ ማር ንግድ*\n\nከፍተኛ ጥራት ያላቸውን የማር ምርቶችን ከኢትዮጵያ እናቀርባለን።",
        'skip': "ለጊዜው ይለፉ"
    }
}

def get_text(lang, key, **kwargs):
    return TRANS.get(lang, TRANS['en']).get(key, key).format(**kwargs)
